# Generated by Django 5.0.6 on 2025-04-05 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Joke content must be at least 10 characters long.'), django.core.validators.MaxLengthValidator(500, message='Joke content cannot exceed 500 characters.')])),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Author name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(100, message='Author name cannot exceed 100 characters.')])),
                ('category', models.CharField(default='general', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='jokes_app_j_categor_a09480_idx')],
            },
        ),
    ]
